apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::852402531991:user/terraformuser
      username: admin
      groups:
        - system:masters

